
volumes:
  payroll-volume:

services:
  db:
    image: mysql:latest
    container_name: payroll-container
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=payrollDb
      - MYSQL_USER=payrollUser
      - MYSQL_PASSWORD=payrollPass
    ports:
      - 3306:3306
    volumes:
      - payroll-volume:/var/lib/mysql