spring.application.name=13-spring-boot-salary-proj

spring.datasource.url=jdbc:mysql://localhost:3306/salaryDb
spring.datasource.username=salaryUser
spring.datasource.password=salaryPass

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
